---
- name: Deploy MiCADO master
  hosts: micado-master
  gather_facts: False

  pre_tasks:
    - name: Ensure that python3 installed
      raw: bash -c "test -e /usr/bin/python3" || (apt -qqy update && apt install -qqy python3-minimal)
      register: output
      changed_when: output.stdout != ""
      tags:
      - build
      - start

    - name: Turn back gather_fact
      setup:
      tags:
      - build
      - start

    - name: Verify OS meets the version requirements (Ubuntu 16.04).
      assert:
        that:
          - "ansible_os_family == 'Debian'"
          - "ansible_distribution_version == '16.04'"
        msg: >
          "The required OS is Ubuntu 16.04"
      tags:
      - build
      - start

    - name: Verify memory requirements (3 GB).
      assert:
        that:
          - "ansible_memtotal_mb >= 2950"
        msg: >
          "The minimum required memory size is 3 GB"
      tags:
      - build
      - start

    - name: "Waiting for automatic security updates to finish"
      script: pre-task/wait-updates.sh
      register: outputsh
      changed_when: outputsh.stdout != ""
      tags:
      - build
      - start

    - name: "Check the CPU manufacture"
      set_fact:
         docker_iivr: false
      when: '"AMD" in  "{{ ansible_processor }}"'
      tags:
      - build
      - start

  roles:
    - role: build-micado-master
      tags:
      - build
    - role: start-micado-master
      tags:
      - start

  vars:

    ######################################################################
    ##### If you want to change the configuration, please edit here. #####
    ######################################################################

    - cloud_cred_path: ./credentials-cloud-api.yml
    - docker_cred_path: ./credentials-docker-registry.yml
    - micado_cred_path: ./credentials-micado.yml

    - disable_worker_updates: True
    - grafana_admin_pwd: secret
    - web_listening_port: 443

    - master_hostname: micado-master
    - worker_hostname: micado-worker

    - docker_iivr: true

    ##################################################################################
    ##### Please do not edit under this line unless you know what you are doing. #####
    ##################################################################################

    - docker_images:
        alertmanager: prom/alertmanager:v0.12.0
        credential_manager: micado/credential-manager:0.2.0
        dashboard: micado/dashboard:0.3.1
        grafana: grafana/grafana:5.1.0
        occopus: micado/occopus:1.7-rc1
        policykeeper: micado/policykeeper:v0.7.3
        prometheus: prom/prometheus:v2.1.0
        redis: redis:4.0
        toscasubmitter: micado/toscasubmitter:dev
        zorp: micado/zorpgpl:6.0.11
        vault: vault:1.0.0
        securitypolicymanager: micado/security-policy-manager:2.0
        crypto_engine: micado/crypto-engine:1.0
        iivr: micado/iivr:1.0
        cadvisor: google/cadvisor:v0.33.0
        node_exporter: prom/node-exporter:v0.15.2
    - docker_package: docker-ce=17.09.1~ce-0~ubuntu
    - kubernetes_version: 1.13.5-00
