---
- include: set-hostname.yml

- include: kubernetes-start.yml

- include: core-config.yml

- include: security-config.yml

- include: occopus-config.yml
  when: enable_occopus

- include: terraform-config.yml
  when: enable_terraform

- include: micado-start.yml

- include: load-auth.yml
  tags:
  - update-auth

- include: security-start.yml

- include: docker-login.yml
  when: docker_cred_path is defined
