---
- name: (System) Setting hostname
  hostname:
    name: "{{ master_hostname }}-{{ ansible_host | replace('.', '-') }}"

- name: (System) Configuring hostfile
  lineinfile:
    mode: '0644'
    path: /etc/hosts
    line: "127.0.0.1 localhost {{ master_hostname }}-{{ ansible_host | replace('.', '-') }}"