---
- name: '(Edge Monitoring) Add NodeExporter HostPath'
  lineinfile:
    path: /var/lib/micado/toscasubmitter/system/nodex.yaml
    insertafter: '^        - containerPort: 9100'
    line: '          hostPort: 9100'
