---
- name: Build MiCADO worker
  hosts: micado
  gather_facts: False

  pre_tasks:
  - name: (Ansible) Include worker pre-tasks
    include_tasks: "{{ item }}"
    loop:
    - "pre-task/10-check-python.yml"
    - "pre-task/15-create-remote-tmp.yml"
    - "pre-task/40-wait-for-updates.yml"

  roles:
    - micado_worker