---
- name: '(Docker) Copy log options'
  copy:
    src: 'docker/daemon.json'
    dest: '/etc/docker/daemon.json'
    mode: 0644
  notify: (Docker) Restart service

- name: '(Docker) Replace ExecStart for systemd'
  lineinfile:
    mode: '0644'
    dest: /lib/systemd/system/docker.service
    regexp: '^ExecStart=/usr/bin/dockerd[.]?'
    line: "ExecStart=/usr/bin/dockerd -H fd:// --exec-opt native.cgroupdriver=systemd --mtu={{ ansible_default_ipv4.mtu }}"
  notify: (Docker) Restart service

- name: (Docker) Flush handlers to restart Docker service
  meta: flush_handlers
