---
- name: Add modules to file
  ansible.builtin.lineinfile:
    path: /etc/modules-load.d/k8s.conf
    create: true
    line: '{{ item }}'
  loop:
  - 'overlay'
  - 'br_netfilter'

- name: Load overlay module
  ansible.builtin.command: modprobe overlay

- name: Load netfilter module
  ansible.builtin.command: modprobe br_netfilter

- name: Add sysctl config
  ansible.builtin.lineinfile:
    path: /etc/sysctl.d/k8s.conf
    create: true
    line: '{{ item }}'
  loop:
  - 'net.bridge.bridge-nf-call-iptables  = 1'
  - 'net.bridge.bridge-nf-call-ip6tables = 1'
  - 'net.ipv4.ip_forward = 1'

- name: Apply sysctl params
  ansible.builtin.command: sysctl --system
