---
- name: 'Copy templates'
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: 0666
  loop:
  - { src: 'iptables/iptables.conf.j2', dest: '/etc/iptables.conf'}
  - { src: 'iptables/ip6tables.conf.j2', dest: '/etc/ip6tables.conf'}
  - { src: 'micado/nodex.yaml.j2', dest: '/var/lib/micado/toscasubmitter/system/nodex.yaml'}
  - { src: 'toscasubmitter/key_config.yml.j2', dest: '/var/lib/micado/toscasubmitter/system/key_config.yml'}
  - { src: 'grafana/data-dashboards-micado.json.j2', dest: '/var/lib/micado/grafana/data/dashboards/micado.json'}
  notify:
  - (iptables) Restart IPv4 service
  - (iptables) Restart IPv6 service