---
- name: (Ansible) Load the cloud credentials from the playbook
  include_vars:
    file: "{{ cloud_cred_path }}"
    name: cloud_cred
  when: cloud_cred_file.stat.exists

- name: (Ansible) Load the gce credentials from the playbook
  include_vars:
    file: "{{ gce_cred_path  }}"
    name: gce_cred
  when: gce_cred_file.stat.exists

- name: (Kubernetes) Store general cloud credentials in secret
  k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: cloud-credentials
        namespace: micado-system
      type: Opaque
      stringData:
        auth_data.yaml: "{{ cloud_cred | to_yaml }}"
  when: cloud_cred_file.stat.exists

- name: (Kubernetes) Store GCE cloud credentials in secret
  k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: gce-credentials
        namespace: micado-system
      type: Opaque
      stringData:
        accounts.json: "{{ gce_cred | to_json }}"
  when: gce_cred_file.stat.exists

- name: (Kubernetes) Store OCI private key in secret
  k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: oci-key
        namespace: micado-system
      type: Opaque
      stringData:
        oci_api_key.pem: "{{ oci_key }}"
  when: oci_key_file.stat.exists