---
- include: set-hostname.yml

- include: core-config.yml

- include: security-config.yml

- include: registry-login.yml
  when: registry_cred_path is defined

- include: k3s-start.yml

- include: cloud-config.yml
  when: enable_terraform or enable_occopus

- include: load-auth.yml
  when: enable_terraform or enable_occopus
  tags:
  - update-auth

- include: micado-start.yml