---
- name: '(Occopus) Copy config templates'
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: '0644'
  loop:
  - { src: 'worker_node/temp_infrastructure_descriptor.yaml.j2', dest: '/var/lib/micado/toscasubmitter/system/infrastructure_descriptor.yaml'}
  - { src: 'worker_node/cloud_init_worker.yaml.j2', dest: '/var/lib/micado/toscasubmitter/system/cloud_init_worker.yaml'}