---
- name: (MiCADO Security) Wait for SPM running state
  kubernetes.core.k8s:
    kind: Deployment
    name: security-policy-manager
    namespace: micado-system
    wait: yes
    wait_timeout: 90
    wait_condition:
      reason: MinimumReplicasAvailable
      status: "True"
      type: Available
  register: spm_running
  until: spm_running is succeeded
  retries: 3
  delay: 10

- name: (MiCADO Security) Get CA for IPSEC (master)
  get_url:  
    url: http://10.97.170.199:5003/v1.0/nodecerts/ca
    dest: /etc/ipsec.d/cacerts/master.pem
  when: spm_running is succeeded
  register: response
  until: response.status_code == 200
  retries: 5
  delay: 10

- name: (MiCADO Security) Get CRT and KEY for IPSEC (master)
  ansible.builtin.uri:
    url: http://10.97.170.199:5003/v1.0/nodecerts
    method: POST
    dest: /tmp/tmp_certs
    body_format: form-multipart
    body:
      cert_common_name: masternode.micado
  when: spm_running is succeeded
  register: nodecerts
  until: nodecerts.status == 200
  retries: 5
  delay: 10

- name: (MiCADO Security) Split PEM IPSec (key)
  command: /usr/bin/openssl pkey -in /tmp/tmp_certs -out /etc/ipsec.d/private/master.key
  when: spm_running is succeeded

- name: (MiCADO Security) Split PEM IPSEC (cert)
  command: /usr/bin/openssl x509 -in /tmp/tmp_certs -out /etc/ipsec.d/certs/master.crt
  when: spm_running is succeeded

- name: (MiCADO Security) Put cert into secrets
  lineinfile:
    mode: '0600'
    path: /etc/ipsec.secrets
    line: ": RSA 'master.key'"

- name: (MiCADO Security) Remove temporary cert bundle
  file:
    path: /tmp/tmp_certs
    state: absent

  # This copy the Master's CA to the occopus directory because occopus will read this file and put it into the cloud-init template.
- name: (MiCADO Security) Copy CA to occopus directory
  command: /bin/cp /etc/ipsec.d/cacerts/master.pem /var/lib/micado/occopus/data/
  when: enable_occopus

- name: (MiCADO Security) Copy CA to terraform directory
  command: /bin/cp /etc/ipsec.d/cacerts/master.pem /var/lib/micado/toscasubmitter/system/
  when: enable_terraform

- name: (MiCADO Security) Restart IPSec
  command: ipsec restart
  when: spm_running is succeeded