---
- name: '(Terraform) Copy cloudinit template'
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: '0644'
  loop:
    - { src: 'worker_node/cloud_init_worker_tf.yaml.j2', dest: '/var/lib/micado/toscasubmitter/system/cloud_init_worker_tf.yaml'}

- name: '(Terraform) Copy required files'
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: '0644'
  loop:
    - { src: 'egi/configure_tf', dest: '/var/lib/micado/toscasubmitter/system/configure_tf'}
    - { src: 'egi/pyGetScopedToken.py', dest: '/var/lib/micado/terraform/preprocess/egi/pyGetScopedToken.py'}
    - { src: 'terraform/prechecks.py', dest: '/var/lib/micado/terraform/preprocess/prechecks.py'}
    - { src: 'terraform/utils.py', dest: '/var/lib/micado/terraform/preprocess/utils.py'}
    - { src: 'terraform/egi_preprocess.py', dest: '/var/lib/micado/terraform/preprocess/egi_preprocess.py'}