################
##  MiCADO hosts connection info
##   hosts.yml
##
##  For local installations use `ansible_connection: local`
##  For SSH, fill fields according to:
##    ssh <ansible_user>@<ansible_host>
################
all:
  hosts:
    micado:
      # Connection info for the MiCADO Master node
      ansible_host: 123.456.78.90
      ansible_connection: ssh
      ansible_user: ubuntu
  # children:
  #   agents:
  #     # Connection info for MiCADO Agents
  #     hosts:
  #       firstagent:
  #         ansible_host: 0.0.0.0
  #         ansible_connection: ssh
  #         ansible_user: ubuntu
  #   edgenodes:
  #     # Connection info for MiCADO Edges
  #     hosts:
  #       edge1:
  #         ansible_host: ip_address_of_edge1
  #         ansible_connection: ssh
  #         ansible_user: ubuntu
