---
- name: (Ansible) Checking the existence of cloud credentials file
  stat: path={{ cloud_cred_path }}
  delegate_to: localhost
  register: cloud_cred_file
  when: cloud_cred_path is defined
  tags:
  - start
  - update-auth

- name: (Ansible) Checking the existence of gce credentials file
  stat: path={{ gce_cred_path }}
  delegate_to: localhost
  register: gce_cred_file
  when: gce_cred_path is defined
  tags:
  - start
  - update-auth

- name: (Ansible) Checking the existence of OCI private key file
  stat: path={{ oci_key_path }}
  delegate_to: localhost
  register: oci_key_file
  when: oci_key_path is defined
  tags:
  - start
  - update-auth

- name: (Ansible) Checking the existence of security settings file
  stat: path={{ micado_cred_path }}
  delegate_to: localhost
  register: security_cred_file
  when: micado_cred_path is defined
  tags:
  - start
