---
- name: '(Occopus) Copy kubeedge cloud_init'
  template:
    src: cloud_init_worker_edge.yaml.j2
    dest: /var/lib/micado/toscasubmitter/system/cloud_init_worker_edge.yaml
    mode: '0644'
  when: enable_occopus

- name: '(Terraform) Copy kubeedge cloud_init'
  template:
    src: cloud_init_worker_tf_edge.yaml.j2
    dest: /var/lib/micado/toscasubmitter/system/cloud_init_worker_tf_edge.yaml
    mode: '0644'
  when: enable_terraform