{
 "title": "MiCADO Grafana Dashboard",
 "description": "MiCADO Grafana Dashboard",
 "tags": [ "micado" ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "node",
    "label": "Node ID",
    "query": "label_values(container_label_com_docker_swarm_node_id)"
   },
   {
    "name": "instance",
    "label": "Hostnames",
    "query": "query_result(count(up{instance=~\".+\"}) by (instance))"
   },
   {
    "name": "stack_namespace",
    "label": "Stack",
    "query": "query_result(count(container_last_seen{container_label_com_docker_swarm_service_name=~\".+\"}) by (container_label_com_docker_swarm_service_name))"
   },
   {
    "name": "service_name",
    "label": "Service",
    "query": "query_result(count(container_last_seen{container_label_com_docker_swarm_service_name=~\".+\", container_label_com_docker_stack_namespace=~\"$stack_namespace\"}) by (container_label_com_docker_swarm_service_name))"
   },
   {
    "name": "proxy",
    "label": "Proxy",
    "query": "query_result(count(container_last_seen{container_label_com_docker_swarm_service_name=~\".+\"}) by (container_label_com_docker_swarm_service_name))"
   },
   { "name": "topk", "label": "Top Cont.", "query": "5,10,20,50,100,1000" },
   {
    "name": "interval",
    "label": "Interval",
    "query": "30s,1m,2m,3m,5m,7m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "master",
    "label": "MasterNode",
    "query": "label_values(node_boot_time, instance)"
   }
  ]
 },
 "panels": [
  { "title": "General Info & Alerts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "count(node_load1)" }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(rate(container_last_seen{container_label_com_docker_swarm_service_name=~\"$stack_namespace\"}[$interval])) by (container_label_com_docker_swarm_service_name)"
    }
   ]
  },
  {
   "title": "Master Node Uptime",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 1 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "time() - node_boot_time{instance=~\"$master:.*\"}"
    }
   ]
  },
  {
   "title": "Alerts Fired In Prometheus",
   "type": "table",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "ALERTS{alertstate=\"firing\"}"
    }
   ]
  },
  { "title": "Resource Usage (average)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Average Node CPU Usage",
   "type": "graph",
   "gridPos": { "h": 5, "w": 11, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100 - (avg(irate(node_cpu{mode=\"idle\",instance=~\"$instance\"}[$interval])) * 100)",
     "legendFormat": "{{host}}"
    },
    { "legendFormat": "{{host}}" }
   ]
  },
  {
   "title": "Average Container CPU Usage",
   "type": "graph",
   "gridPos": { "h": 5, "w": 13, "x": 11, "y": 7 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "avg(irate(container_cpu_usage_seconds_total{container_label_com_docker_swarm_service_name=~\"$service_name\"}[$interval]) * 100)"
    }
   ]
  },
  {
   "title": "Resource Usage (per Node/Container)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 }
  },
  {
   "title": "CPU usage per node",
   "type": "graph",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100 - (avg by (instance) (irate(node_cpu{mode=\"idle\",instance=~\"$instance\"}[$interval])) * 100)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "CPU Usage per Container (Stacked)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 13, "x": 11, "y": 13 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": " label_replace(topk($topk, sum without (cpu) (irate(container_cpu_usage_seconds_total{container_label_com_docker_swarm_service_name=~\"$service_name\",container_label_com_docker_swarm_node_id=~\"$node\",id=~\"/docker/.*\"}[1m])) * 100), \"task_name\", \"$1\", \"container_label_com_docker_swarm_task_name\", \"(.*\\\\.[a-z0-9]{1,3}).*\\\\..*\")",
     "legendFormat": "{{task_name}}"
    }
   ]
  },
  {
   "title": "Memory usage per node",
   "type": "graph",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemTotal - node_memory_Inactive",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Memory Usage per Container (Stacked)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 13, "x": 11, "y": 21 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "label_replace(topk($topk, sum(container_memory_usage_bytes{container_label_com_docker_swarm_service_name =~\"$service_name\",container_label_com_docker_swarm_node_id=~\"$node\"}) by (name, container_label_com_docker_swarm_task_name)), \"task_name\", \"$1\", \"container_label_com_docker_swarm_task_name\", \"(.*\\\\.[0-9]*).*\\\\..*\")",
     "legendFormat": "{{task_name}}"
    }
   ]
  },
  { "title": "Network Traffic", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 } },
  {
   "title": "Network Traffic on Cluster",
   "type": "graph",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total[$interval]))",
     "legendFormat": "RECEIVED"
    },
    {
     "expr": "- sum(rate(container_network_transmit_bytes_total[$interval]))",
     "legendFormat": "SENT"
    }
   ]
  },
  {
   "title": "Received Network Traffic per Container (stacked)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 13, "x": 11, "y": 30 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "label_replace(topk($topk,sum(rate(container_network_receive_bytes_total{container_label_com_docker_stack_namespace=~\"$stack_namespace\",container_label_com_docker_swarm_service_name=~\"$service_name\",container_label_com_docker_swarm_service_name!~\"$proxy\",container_label_com_docker_swarm_node_id=~\"$node\"}[$interval])) by (name, container_label_com_docker_swarm_task_name)), \"task_name\", \"$1\", \"container_label_com_docker_swarm_task_name\", \"(.*\\\\.[a-z0-9]{1,3}).*\\\\..*\")",
     "legendFormat": "{{task_name}}"
    }
   ]
  },
  {
   "title": "Versions",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 },
   "collapsed": true,
   "panels": [
    {
     "title": "Versions",
     "type": "table",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 44 },
     "targets": [
      {
       "expr": "cadvisor_version_info",
       "legendFormat": "{{instance}} cAdvisor Version: {{cadvisorVersion}}"
      },
      {
       "expr": "prometheus_build_info",
       "legendFormat": "{{instance}} Prometheus Version: {{version}}"
      },
      {
       "expr": "node_exporter_build_info",
       "legendFormat": "{{instance}} Node-Exporter Version: {{version}}"
      },
      {
       "expr": "cadvisor_version_info",
       "legendFormat": "{{instance}} Docker Version: {{dockerVersion}}"
      },
      {
       "expr": "cadvisor_version_info",
       "legendFormat": "{{instance}} Host OS Version: {{osVersion}}"
      },
      {
       "expr": "cadvisor_version_info",
       "legendFormat": "{{instance}} Host Kernel Version: {{kernelVersion}}"
      }
     ]
    }
   ]
  }
 ]
}