---
- name: Populate service facts
  service_facts:

- name: (edge) Copy install script
  template:
    src: get-micado-edge.sh.j2
    dest: /tmp/get-micado-edge.sh
    mode: '0777'
  when: '"edgecore.service" not in services'

- name: (edge) Install MiCADO Edge
  command: /tmp/get-micado-edge.sh
  when: '"edgecore.service" not in services'