pre_authentication:
- type: openid
  auth_data: &OPENID
    # Use this anchor for generating OpenID Connect access tokens (see nova)
    url:
    client_id:
    client_secret:
    refresh_token:

resource:
- type: ec2
  auth_data:
    accesskey: 
    secretkey: 

- type: cloudsigma
  auth_data:
    email:
    password:

- type: cloudbroker
  auth_data:
    email: 
    password: 

- type: nova
  auth_data:
    # Select your authentication method
    # v3.Password
    username: 
    password:
    domain_name:
    # v3.ApplicationCredential
    application_credential_id:
    application_credential_secret:
    # v3.OidcAccessToken (access_token can instead be the literal token)
    identity_provider:
    access_token: *OPENID

- type: azure
  auth_data:
    # Select your authentication method
    # Only subscription_id is required for auth with Managed Service Identity
    subscription_id:
    # Optional (additional parameters for auth with Service Principal)
    client_id:
    client_secret:
    tenant_id:

- type: oci
  auth_data:
    # Select your authentication method
    # Fill these parameters ONLY if you are using API Key based authentication
    tenancy_ocid:
    user_ocid:
    fingerprint:

# For Google Cloud, instead populate the credentials-gce.json file
