---
- name: (Docker) Begin containerd installation
  include_role:
    name: common
    tasks_from: container-runtime-setup

- name: (Kubernetes) Begin Kubernetes installation
  include_role:
    name: common
    tasks_from: kubernetes-install

- include: worker-deps.yml

- name: (MiCADO Monitoring) Prepare Monitoring
  include_role:
    name: common
    tasks_from: pull-monitoring
