---
- name: (Docker) Begin Docker installation
  include_role:
    name: common
    tasks_from: docker-install

- name: (Docker) Begin Docker configuration
  include_role:
    name: common
    tasks_from: docker-configure

- name: (Kubernetes) Begin Kubernetes installation
  include_role:
    name: common
    tasks_from: kubernetes-install

- include: worker-deps.yml

- name: (MiCADO Monitoring) Prepare Monitoring
  include_role:
    name: common
    tasks_from: pull-monitoring
